### ISSUE TITLE
Port original gk-pilot python logic to initiate

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-gk-python#1]
Port over any logic from the original python gk-pilot source code (and was later rebuilt in clojure in the same project).

**Comment by larrybabb** [comment]
1. setup the repo clinvar-gk-python (to supercede clinvar-gk-pilot)
2. configured packages (pyproject.toml)
3. created baseline main.py script from portions of original python script that are useful (processline, args, ...)
4. setup linter script for use by devs in local pre-commit hooks
5. simplify main.py to read a gcp bucket file (and that's all)
6. add logging

**Comment by theferrit32** [comment]
I think this is all done except for (5). I would recommend closing and creating a separate issue to represent the work @toneillbroad is doing to read the `variation_identity` files.
